### ISSUE TITLE
Bug in Worksheet 7 Solution

### ISSUE THREAD

**Issue by KevinLaurence** [CamJam-EduKit/EduKit1#3]
The method button.ispressed caused an error in my case at line 130.

https://github.com/CamJam-EduKit/EduKit1/blob/39001a8040f11bdf5557738e15542ae8bc71dc9c/CamJam%20EduKit%201%20-%20GPIO%20Zero/Code%20(GPIO%20Zero)/7-TrafficLights-solution.py#L130

I think it should be `if button.is_pressed:`. The code ran successfully once I made that change.

**Comment by GeekyTim** [comment]
Fixed
